buddy-minelev-api:
  # image: telemark/buddy-minelev-api
  build: .
  environment:
    SERVER_PORT: 3000
    JWT_SECRET: NeverShareYourSecret
    YAR_SECRET: NeverShareYourSecret
    # Logger
    #ENV SLACK_ENABLED true # Uncomment to enable
    SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/xxx/xxx/xxx"
    SLACK_CHANNEL: logging
    SLACK_USERNAME: loggerBot
    # Buddy
    BUDDY_USERNAME: username
    BUDDY_PASSWORD: password
    BUDDY_SERVER: hostmain.domain.no
    BUDDY_DATABASE: dbMetakatalog
    # Extens
    ATFERD_GROUP: "/151ATF"
    ORDEN_GROUP: "/151ORD"
    PROVE_GROUP: "/151KP"
  ports:
    - "3000:3000"
